# -*- coding: utf-8 -*-
"""forgeall_timestamp_generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ke-NaYjiPFkIFDLDvgBd0e7SN1m8HQpy
"""

def fa_print_current_timestamp_in_pst():
    """
    Prints the current timestamp in Pacific Standard Time (PST).
    """


    from datetime import datetime
    import pytz

    # Get the current UTC time
    current_time_utc = datetime.now(pytz.utc)

    # Convert the current time to PST (Pacific Standard Time)
    pst_timezone = pytz.timezone('US/Pacific')
    current_time_pst = current_time_utc.astimezone(pst_timezone)

    # Print the current timestamp in PST with proper formatting
    print("Current Timestamp in PST:", current_time_pst.strftime("%Y-%m-%d %H:%M:%S %Z"))

# Call the function to print the timestamp
#fa_print_current_timestamp_in_pst()

