# -*- coding: utf-8 -*-
"""inflate-deduped-to-ground-truth.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trcXyxv_F5WQohXIp7-xvwkTHGT5jxxH
"""

import pandas as pd

def replicate_rows_by_column_value(input_csv, output_csv):
    # Read the CSV file into a DataFrame
    df = pd.read_csv(input_csv)

    # Check that the 'Duplicate_Count' column is present
    if 'Duplicate_Count' not in df.columns:
        raise ValueError("Input CSV must have a 'Duplicate_Count' column.")

    # Repeat each row according to its 'Duplicate_Count' value
    df_replicated = df.loc[df.index.repeat(df['Duplicate_Count'])]

    # (Optional) Reset the index
    df_replicated.reset_index(drop=True, inplace=True)

    # Save the result to a new CSV
    df_replicated.to_csv(output_csv, index=False)

# Example usage
if __name__ == '__main__':
    replicate_rows_by_column_value('data_with_phases_and_calcs.csv', 'rebuilt_using_calphad_data.csv')